mysite/django-polls/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/poll_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # polls url
    path('polls/', include('polls.urls')),
    # admin
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/vote_data/', views.vote_data, name='vote_data'),
]

mysite/django-polls/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/pages/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/django-polls/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# if you used render method \httpresponse and loader is no longer needed
# from django.http import HttpResponse
# from django.template import loader

''' GENERIC VIEW '''
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# def index(request):
#     # return HttpResponse("Hello, world. You're at the polls index.")
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#
#     # shortcut
#     return render(request, 'polls/index.html', context)
#
#     # longcut
#     # return HttpResponse(template.render(context, request))
#
# def detail(request, question_id):
#     # return HttpResponse("You're looking at question %s." % question_id)
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     # response = "You're looking at the results of question %s."
#     # return HttpResponse(response % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/pages/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'pages/index.html')

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.http import JsonResponse
from django.forms.models import model_to_dict


from .models import Choice, Question


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
def get_queryset(self):
    """
    Return the last five published questions (not including those set to be
    published in the future).
    """
    return Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:5]

def vote_data(request, question_id):
    choices = Choice.objects.filter(question=question_id).values()
    data = {
        'labels': [x['choice_text'] for x in choices],
        'votes': [x['votes'] for x in choices],
    }
    return JsonResponse(data)

mysite/polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <title>Pollster {% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

mysite/polls/templates/partials/_navbar.html
<nav class="navbar mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Boom Pollster</a>
	</div>
</nav>

mysite/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome To Boom Pollster</h1>
    <p>This is an example Django polling app</p>
    <a class="btn btn-dark" href="{% url 'polls:index' %}">
        View Available Polls</a
      >
  </div>
  </div>
{% endblock %}

mysite/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ question.question_text }}
{% endblock%}

{% block content %}

<h3>{{ question.question_text }}</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <p>
        <label for="choice{{ forloop.counter }}">
            <input class="with-gap" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <span>{{ choice.choice_text }}</span>
        </label>
    </p>
{% endfor %}
<button class="btn waves-effect waves-light blue lighten-1" type="submit" name="action">
    Vote
</button>
<a class="waves-effect waves-light btn red lighten-2" href="{% url 'polls:index'%}">Go back</a>
</form>

{% endblock %}

mysite/templates/polls/index.html
{% extends 'base.html' %}


{% block title %}
    {{ question.question_text }}
{% endblock%}

{% block content %}
{% if latest_question_list %}
    <div class="row">
        {% for question in latest_question_list %}
            <div class="col s12 m6">
                <div class="card light-blue lighten-5">
                    <div class="card-content black-text">
                    <span class="card-title">{{ question.question_text }}</span>
                    <p>{{ question.pub_date }}</p>
                    </div>
                    <div class="card-action">
                        <a class="waves-effect waves-light btn" href="{% url 'polls:detail' question.id %}">Visit</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

mysite/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}
    {{ question.question_text }}
{% endblock%}

{% block content %}

<div class="row">
    <h3 style="text-align: center">{{ question.question_text }}</h3>
    <div style="text-align: center" class="col s6 offset-s3">
        <canvas height="200" width="200" id="myChart">
            <strong>No votes yet</strong>
        </canvas>
    </div>
    <div style="text-align: center" class="col s6 offset-s3">
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>
    </div>
    <div style="text-align: center" class="col s6 offset-s3">
        <a style="margin-bottom: 10px;" class="waves-effect waves-light btn blue lighten-2" href="{% url 'polls:detail' question.id %}">Vote again?</a>
        <a style="margin-bottom: 10px;" class="waves-effect waves-light btn red lighten-2" href="{% url 'polls:index'%}">Go back</a>
    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<script type="text/javascript">
$.ajax({
    method: "GET",
    url: '{% url "polls:vote_data" question.id %}',
    success: function(data) {
        console.log(data)
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: data.labels,
                datasets: [{
                    label: '# of Votes',
                    data: data.votes,
                    backgroundColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ]
                }]
            }
        });
    },
    error: function(error_data) {
        console.log(error_data)
    }
})
</script>
{% endblock %}